database:
  name: cn.edu.gzmu.center.verticle.DatabaseVerticle
  configuration:
    name: auth-center-db
    port: 5432
    host: 127.0.0.1
    database: gzmu
    user: postgres
#    password: "147258369"
    password: "123456"
    maxSize: 5
web:
  name: cn.edu.gzmu.center.verticle.WebVerticle
  configuration:
    name: auth-center-web
    server:
      port: 8889
    oauth:
      server: http://118.24.1.170:8888
      token: /oauth/token
      authorization: /oauth/authorize
      token-info: /oauth/check_token
      client-id: gzmu-auth
      client-secret: gzmu-auth-secret
      redirect-uri: http://127.0.0.1:8081/#/login
      scope: READ
      logout-uri: /oauth/logout
      logout-redirect-url: http://127.0.0.1:8081/#/logout
      security: false
